"""update migration

Revision ID: 898f0bbfa3a8
Revises: 4e5c596b039e
Create Date: 2024-07-30 03:34:11.493461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "898f0bbfa3a8"
down_revision: Union[str, None] = "4e5c596b039e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_accesstokens_created_at", table_name="accesstokens")
    op.drop_table("accesstokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accesstokens",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "token", sa.VARCHAR(length=43), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="accesstokens_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name="accesstokens_pkey"),
    )
    op.create_index(
        "ix_accesstokens_created_at",
        "accesstokens",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
