"""add photo column

Revision ID: 2b83e356e0eb
Revises: 02111204275c
Create Date: 2024-07-29 21:26:22.116618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b83e356e0eb"
down_revision: Union[str, None] = "02111204275c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wishcards", sa.Column("photo", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wishcards", "photo")
    # ### end Alembic commands ###
